CREATE SCHEMA IF NOT EXISTS sales;

CREATE SCHEMA IF NOT EXISTS petshop;

CREATE SCHEMA IF NOT EXISTS humanresource;

CREATE SCHEMA IF NOT EXISTS supply;

CREATE SCHEMA IF NOT EXISTS history;

CREATE SCHEMA IF NOT EXISTS dictionary;